#!/bin/bash -evx
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

DIR="$(pwd)"
if [ -d "$DIR/debian/luwrain-snapshot" ]; then
    DEST_DIR="$DIR/debian/luwrain-snapshot/usr/share/luwrain"
        BIN_DIR="$DIR/debian/luwrain-snapshot/usr/bin"
else
        DEST_DIR="$DIR/debian/luwrain/usr/share/luwrain"
        BIN_DIR="$DIR/debian/luwrain/usr/bin"
fi

. base/scripts/init.sh

cd base/scripts
mkdir -p "$DEST_DIR/bin"

cat <<EOF > "$DEST_DIR/bin/luwrain"
#!/bin/bash -e
# Runs the LUWRAIN platform
# Copyright $(date +%Y) Michael Pozhidaev <msp@luwrain.org>

cd /usr/share/luwrain
exec java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.web,javafx.swing --add-exports javafx.web/com.sun.webkit.dom=ALL-UNNAMED -jar jar/luwrain-base.jar "\$@"
EOF

cat <<EOF > "$DEST_DIR/bin/lwr"
#!/bin/bash -e
# Runs the LUWRAIN platform blocking any output
# Copyright $(date +%Y) Michael Pozhidaev <msp@luwrain.org>

exec luwrain "\$@" > /dev/null 2>&1
EOF
chmod 755 "$DEST_DIR/bin/luwrain" "$DEST_DIR/bin/lwr"

./lwr-basedirs-linux "$DEST_DIR"

cd $DEST_DIR
wget -q https://download.luwrain.org/compilation/rhvoice-data.tar.xz
tar xf rhvoice-data.tar.xz
rm -f rhvoice-data.tar.xz

cd jar
rm -f javafx-*.jar
ln -s luwrain-base-*.jar luwrain-base.jar

mkdir -p "$BIN_DIR"
ln -s /usr/share/luwrain/bin/luwrain "$BIN_DIR/luwrain"
ln -s /usr/share/luwrain/bin/lwr "$BIN_DIR/lwr"
